### ISSUE TITLE
mpeg-dash Video is stalled on "play start" but the audio is playing smoothly

### ISSUE THREAD

**Issue by peyoh** [google/ExoPlayer#1653]
Hello, 
We are using mpeg-dash as protocol with shacka packager for live streaming. Just after the start, sometimes the video is stalled, but the audio is playing. After 1-5 seconds the scene jumps to a new position and the A and V are now synced. 
This can be reproduced with the exoplayer demo app also.  
I'm not sure if this is a problem in exoplayer or in the shaka packager or in the transcoding system. 
On the developers email I've provided two example urls. Can you give us some idea what is wrong?

**Comment by peyoh** [comment]
Hello,
we've changed transcoder backend and packetizer to Nimble, but with no effect. 
On dev.exoplayer@gmail.com I've send example URL. Maybe somebody can help. 
With dash.js, bitmovin and shaka-player this issue doesn't exists, btw.

**Comment by ojw28** [comment]
The link provided is either dead or geo-restricted, so we're unable to test. I'm pretty sure this is fixed in ExoPlayer V2 though. Try with the latest code from `dev-v2` branch (note: V2 is not yet completely stable, but you should be able to validate this).

**Comment by peyoh** [comment]
Hello, 
the issue is still there. 
Sorry about the link. I've provided new one at the dev email.

**Comment by ojw28** [comment]
I was able to reproduce in V1, but not in V2. I'm pretty sure the issue is fixed. Were you testing using the very latest `dev-v2` branch when you were able to reproduce the issue?

**Comment by peyoh** [comment]
Sorry about.. 
I had this one: dev-2.X.X-experimental
With dev-2 is ok. 
Thank you.
