### ISSUE TITLE
MKV file with Opus Audio and VP9 video plays like a distorted one

### ISSUE THREAD

**Issue by nerd-sj** [google/ExoPlayer#3080]
### Issue description
MKV video file plays like a slow moving file and audio is shrill

### Reproduction steps
1. Get a MKV container format file with x-vnd.on2.VP9 as Video format and Opus as Audio format and  1920 * 1080p resolution.
2. Build the demo app with extensions or no extensions. 
3. Edit the demo app PlayerActivity manifest to accept video/* mimetype and
    "android.intent.action.VIEW" action . 
4. Go to any file manager and select the video file and play with ExoPlayer.
5. Video plays as if its a slow-mo and the audio is totally shrill and distorted.

### Link to test content
Mailed

### Version of ExoPlayer being used
Version : 2.4.3 (dev-v2 branch or release branch)

### Device(s) and version(s) of Android being used
Device : OnePlus One (A0001)
Android Version : 7.1.2

### A full bug report captured from the device
Mailed

**Comment by ojw28** [comment]
The bug report seems to have been captured whilst using the Opus extension. Please can you capture a bug report when not using it? Thanks.

**Comment by ojw28** [comment]
I think the media file broken. In the Matroska container the Opus track has its SamplingFrequency element set to 24000, when it should be 48000. If it were set to 48000 playback would work successfully.

**Comment by nerd-sj** [comment]
I can play the file properly in Samsung S8 Edge with the default video player itself. If this can play file properly why not ExoPlayer?

**Comment by ojw28** [comment]
The sample rate is specified both in the container (SamplingFrequency element) and in the OpusHeader

**Comment by ojw28** [comment]
I think I may have misunderstood how Opus decoders work. From reading around a little, it sounds like Opus decoders may always decode at 48000Hz regardless of the sample rate in which the media was encoded. When using a platform decoder this should be handled at the decoder level (and ExoPlayer does play this content successfully on an S8 when using the platform decoder rather than the Opus extension). For the Opus extension, if LibOpus always decodes to 48000Hz, we can probably just hardcode that, which would result in this piece of media playing successfully.

I still think the media file is broken. I think it should itself be hardcoding the SamplingFrequency element to 48000, as is stated in the [specification](https://wiki.xiph.org/MatroskaOpus).

**Comment by ojw28** [comment]
Fixed for real in `dev-v2`. Thanks for re-pinging!

**Comment by nerd-sj** [comment]
Now the audio plays fine but file is still not seekable. I checked playing the file in One Plus 3T from Gallery app and also with MX Player (both SW and HW decoders in that) . Its seeking fine there. Also it works with MX Player (HW+ decoder) on One Plus One.

**Comment by nerd-sj** [comment]
Any plans to fix this?

**Comment by ojw28** [comment]
I didn't spend much time looking at this, but the extractor isn't finding what it needs to seek within the file. Specifically, there doesn't seem to be an entry in the Meta Seek Information specifying the position of the Cues element (i.e. the index that enables efficient seeking). It looks like there is a Cues element at the end of the file, but because there's no corresponding entry in the Meta Seek Information at the start of the file, we're unable to find it until it's too late.

We do not support seeking in media unless the media is packaged to allow seeking in an efficient way, and have no plans to change this policy. To enable seeking, I think you should ensure the Cues element can be found by adding a corresponding Meta Seek Information entry.
