### ISSUE TITLE
Amlogic TV box: Jerky playback on TS file that plays ok with MediaPlayer

### ISSUE THREAD

**Issue by elsparro** [google/ExoPlayer#3316]
### Issue description
Choppy playback, seems like the frames are out of order or have wrong timestamps.
Playing via Android MediaPlayer API gives a smooth playback.

### Reproduction steps
Put the link http://88.206.183.75/support/svt1hd_terrest_5min.ts in the media.exolist.json file, build and run.

### Link to test content
http://88.206.183.75/support/svt1hd_terrest_5min.ts

### Version of ExoPlayer being used
r2.5.3

### Device(s) and version(s) of Android being used
Amlogic Quad-Core Enjoy TV Box (Android 6.0.1, API 23)

### A full bug report captured from the device
Attached.

**Comment by elsparro** [comment]
[bug.txt](https://github.com/google/ExoPlayer/files/1348425/bug.txt)

**Comment by shaoyangdl** [comment]
I have got the same issue on Amlogic devices. I haven't tried on any other devices. It seems to keep feeding data to extractor and extractor is waiting buffering without playing until to getting out of memory.

**Comment by shaoyangdl** [comment]
E/LoadTask: OutOfMemory error loading stream
                                                                 java.lang.OutOfMemoryError: Failed to allocate a 65548 byte allocation with 23672 free bytes and 23KB until OOM
                                                                     at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
                                                                     at com.google.android.exoplayer2.source.SampleQueue.preAppend(SampleQueue.java:592)
                                                                     at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:532)
                                                                     at com.google.android.exoplayer2.extractor.ts.H264Reader.consume(H264Reader.java:114)
                                                                     at com.google.android.exoplayer2.extractor.ts.PesReader.consume(PesReader.java:132)
                                                                     at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:296)
                                                                     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:704)
                                                                     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by shaoyangdl** [comment]
It is solved to by setting FLAG_ALLOW_NON_IDR_KEYFRAMES flags. [https://github.com/google/ExoPlayer/issues/1894](url)

**Comment by elsparro** [comment]
Forgot to write that this flag is set, without it the file won't play at all.
But the playback is still very jerky so it's it not solved, some debug printing revealed that the timestamps coming back from the MediaCodec is not the same as going in.

**Comment by andrewlewis** [comment]
Is playback of this stream choppy if you disable the audio track? Can you reproduce the problem on any other devices? MediaCodec may reorder buffers from decode to presentation order, so a discrepancy is not necessarily an indication that anything is going wrong.

**Comment by andrewlewis** [comment]
The stream plays fine on a 2015 Sony Android TV, so this is probably device-specific.

**Comment by ojw28** [comment]
Closing as I'm not sure there's anything actionable for us to do here. Please report the issue to AmLogic. Thanks!
