### ISSUE TITLE
mp3 files are not playing on some devices

### ISSUE THREAD

**Issue by pratikpradhan** [google/ExoPlayer#377]
Hi,

We are trying to play mp3 files and it is giving mediacodecexception on some devices.
Device: HTC One
Exoplayer Release: 1.2.3

From the exception looks like it is not able to find class which will be able to play the file.
The mime-type is audio/mpeg.
MediaFormat(audio/mpeg, -1, -1, -1, -1.0, 2, 44100, -1, -1, -1) OR
MediaFormat(audio/mpeg, -1, -1, -1, -1.0, 1, 16000, -1, -1, -1)

weird part his android's native media player plays it well
Following exception is seen in logcat.

```
04-01 15:23:42.860: E/dalvikvm(25158): Could not find class 'android.media.MediaCodec$CodecException', referenced from method com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException.getDiagnosticInfoV21
04-01 15:23:42.860: W/dalvikvm(25158): VFY: unable to resolve instanceof 174 (Landroid/media/MediaCodec$CodecException;) in Lcom/google/android/exoplayer/MediaCodecTrackRenderer$DecoderInitializationException;
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): Internal track renderer error.
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: [-49998], MediaFormat(audio/mpeg, -1, -1, -1, -1.0, 1, 16000, -1, -1, -1)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:372)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:337)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:736)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:504)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:481)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:422)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:211)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at android.os.Looper.loop(Looper.java:155)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at android.os.HandlerThread.run(HandlerThread.java:60)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:43)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: [-49998], MediaFormat(audio/mpeg, -1, -1, -1, -1.0, 1, 16000, -1, -1, -1)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:339)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	... 9 more
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): Caused by: com.google.android.exoplayer.MediaCodecUtil$DecoderQueryException: Failed to query underlying media codecs
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfo(MediaCodecUtil.java:140)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfo(MediaCodecUtil.java:113)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfo(MediaCodecUtil.java:72)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:334)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	... 9 more
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): Caused by: java.lang.IllegalArgumentException
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at android.media.MediaCodecList.getCodecCapabilities(Native Method)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at android.media.MediaCodecInfo.getCapabilitiesForType(MediaCodecInfo.java:211)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfoInternal(MediaCodecUtil.java:164)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfo(MediaCodecUtil.java:135)
04-01 15:23:42.930: E/ExoPlayerImplInternal(25158): 	... 12 more
```

**Comment by Nezz** [comment]
We have received similar reports from our users.

**Comment by ojw28** [comment]
This is a device specific issue, and will likely require a device specific workaround. Can you provide a more complete list of the (device, OS-build) combinations that you know to be affected?

**Comment by pratikpradhan** [comment]
Here are the device details:
Model: HTC One S
OS: Android 4.1.1
HTC SDK API 4.65
HTC Extension Version Sense 45_5
HTC Software No: 3.19.720.100
Kernel Version: 3.4.10-G4E8A4AF

**Comment by th3hamm0r** [comment]
I think I have a similar issue with a HTC Desire X and the latest ExoPlayer Demo (1.3.2) when playing the "Google Play (MP3 Audio)" sample.

The device:
OS: Android 4.1.1
HTC SDK API 4.65
HTC Extension Version: HTCExtension_Sense45_9
Kernel Version: 3.4.0-g86f8a9f
Build No: 2.20.169.8

Log output:
```
05-22 11:09:39.850    6645-7883/com.google.android.exoplayer.demo E/ExoPlayerImplInternal﹕ Internal track renderer error.
    com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: [-49998], MediaFormat(audio/mpeg, 4096, -1, -1, -1.0, 2, 44100, 59271836, -1, -1)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:387)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:352)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:735)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:516)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:496)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:155)
            at android.os.HandlerThread.run(HandlerThread.java:60)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: [-49998], MediaFormat(audio/mpeg, 4096, -1, -1, -1.0, 2, 44100, 59271836, -1, -1)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:352)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:735)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:516)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:496)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:155)
            at android.os.HandlerThread.run(HandlerThread.java:60)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.MediaCodecUtil$DecoderQueryException: Failed to query underlying media codecs
            at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfo(MediaCodecUtil.java:125)
            at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfo(MediaCodecUtil.java:104)
            at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfo(MediaCodecUtil.java:68)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.getDecoderInfo(MediaCodecTrackRenderer.java:301)
            at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.getDecoderInfo(MediaCodecAudioTrackRenderer.java:136)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:350)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:735)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:516)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:496)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:155)
            at android.os.HandlerThread.run(HandlerThread.java:60)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: java.lang.IllegalArgumentException
            at android.media.MediaCodecList.getCodecCapabilities(Native Method)
            at android.media.MediaCodecInfo.getCapabilitiesForType(MediaCodecInfo.java:211)
            at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfoInternal(MediaCodecUtil.java:144)
            at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfo(MediaCodecUtil.java:121)
            at com.google.android.exoplayer.MediaCodecUtil.getMediaCodecInfo(MediaCodecUtil.java:104)
            at com.google.android.exoplayer.MediaCodecUtil.getDecoderInfo(MediaCodecUtil.java:68)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.getDecoderInfo(MediaCodecTrackRenderer.java:301)
            at com.google.android.exoplayer.MediaCodecAudioTrackRenderer.getDecoderInfo(MediaCodecAudioTrackRenderer.java:136)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:350)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.onInputFormatChanged(MediaCodecTrackRenderer.java:735)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.readFormat(MediaCodecTrackRenderer.java:516)
            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:496)
            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:401)
            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:203)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:155)
            at android.os.HandlerThread.run(HandlerThread.java:60)
            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
```

**Comment by andrewlewis** [comment]
I was able to reproduce the problem on an HTC Butterfly device, and found that the process crashes if the failing codec OMX.qcom.audio.decoder.mp3 is created, with OMX_ErrorComponentNotFound output.

We will have to filter out that codec on devices where the error was thrown. Please could you provide the output of 'adb shell getprop ro.build.fingerprint' on any devices where you saw this issue? Thanks!

**Comment by th3hamm0r** [comment]
@andrewlewis, I'm happy to hear that and I will post the output tomorrow!

**Comment by th3hamm0r** [comment]
@andrewlewis, here is the output for the HTC Desire X I mentioned above:
    
    htc/vodafone_at/protou:4.1.1/JRO03C/162361.8:user/release-keys

**Comment by brianchu** [comment]
I am curious by 'device specific workaround', does it mean the player will automatically fall back to use native player or do we (the caller) need to do something else? Also where is the database of these problematic devices? Are they inside this repository?

**Comment by andrewlewis** [comment]
@th3hamm0r, thanks!

@brianchu, the devices I've tested all have another MP3 decoder that does not exhibit this problem, so the fix is for ExoPlayer to ignore the 'broken' codec when enumerating decoders. This will be automatic, so the app doesn't have to do anything. For now, there is no database of problematic codec names -- we will just check for the product/API version/codec name combination in code in MediaCodecUtil.java. I expect we will merge this into the dev branch today.

**Comment by Ood-Tsen** [comment]
Hello @andrewlewis ,

Can we hand over to next suitable codec if receive DecoderInitializationException ?

**Comment by andrewlewis** [comment]
Fixed in dev. Other affected devices can be added in the same way.

@Ood-Tsen, we are working around this issue in ExoPlayer, so the application does not have to do anything.

**Comment by th3hamm0r** [comment]
@andrewlewis, I pulled the latest dev and still get the same error.
One thing to note is that `Util.Product` is "vodafone_at" in my case. `android.os.Build.DEVICE` instead contains the expected "protou" string.
But even if I change it to the DEVICE's value, it fails.

**Comment by th3hamm0r** [comment]
Ok, with my own prototype with custom mp3 files the DEVICE constant fixed the issue. But also @Ood-Tsen's solution worked!
I may have a problem with my (clean) ExoPlayer demo, but the mp3 sample there does not work with any of those fixes.

**Comment by andrewlewis** [comment]
On HTC Butterfly these values happened to match, but Build.DEVICE is the right one to use. I will submit a fix.

**Comment by andrewlewis** [comment]
@th3hamm0r, the MP3 demo should now work on a clean dev branch. Please could you try to verify this fix again, as I don't have access to an HTC Desire X to test it? Sorry for the inconvenience.

The reason getting capabilities for this OMX component fails seems to be that MediaCodec can't communicate with mediaserver. (And instantiating the component always crashes mediaserver, which might be related.) Skipping over codecs on catching IllegalArgumentException is risky because a codec could be skipped due to a transient failure, which could cause poor quality playback due to falling back to using a software codec, for example.

**Comment by Ood-Tsen** [comment]
Yes @andrewlewis, I agree - it may get poor video quality by using software decoder.
But in this case is mp3, it should be safe for @th3hamm0r .

I think a programmer should know "pro and con" of each solution and pick a one.

**Comment by th3hamm0r** [comment]
@andrewlewis, works! Thanks, for the quick response!

**Comment by andrewlewis** [comment]
@Ood-Tsen, I still think catching the exception and continuing is risky. We know that the exception is thrown when the MediaCodecInfo instance can't communicate with the mediaserver, and that instantiating the component causes mediaserver to crash. I think it is possible that the mediaserver could be put in a bad state just by querying for capabilities of the 'broken' OMX component. Since this will only affect a small number of device/build combinations, the targeted workaround seems safer.

**Comment by AriMeidan** [comment]
Hello, a client of mine expiriencing this error on HTC One S. I read here that the application does not need to do anything in order for it to work, but it still throws the exception. I'm using version 1.4.2.
What should i do?

**Comment by pratikpradhan** [comment]
Here is what we did,
For mp3 playback we used native MediaPlayer and for rest ExoPlayer earlier. But now with latest release 1.5.3 we moved completely to ExoPlayer and we not yet seen any issue.

**Comment by ernhelm** [comment]
On Dec 17, 2015 1:57 AM, "pratikpradhan" <notifications@github.com> wrote:
>
> Here is what we did,
> For mp3 playback we used native MediaPlayer and for rest ExoPlayer
earlier. But now with latest release 1.5.3 we moved completely to ExoPlayer
and we not yet seen any issue.

**Comment by AriMeidan** [comment]
This is how i create a renderer, is this correct?

    public void prepare(Uri data){
        ExtractorSampleSource sampleSource = new ExtractorSampleSource(
                data, dataSource, allocator, BUFFER_SEGMENT_COUNT * BUFFER_SEGMENT_SIZE);
        MediaCodecAudioTrackRenderer audioRenderer = new MediaCodecAudioTrackRenderer(sampleSource);

        exoPlayer.prepare(audioRenderer);
    }

**Comment by powerqian** [comment]
Hi @andrewlewis , I'm wondering why not adding HTC One S, which is the original issue reporter's device here https://github.com/google/ExoPlayer/issues/377#issuecomment-90798548, to the device checking list?

The Util.DEVICE is `villec2` on the device. Without adding it, ExoPlayer fails to play the MP3.

**Comment by ojw28** [comment]
We'll get that one added to the list, thanks!

**Comment by powerqian** [comment]
Hi @ojw28 thanks for the quick follow up. May I ask when will the next version which includes this fix be released?
