### ISSUE TITLE
IMA Extension behaving weird when backgrounding midrolls with multiple ads

### ISSUE THREAD

**Issue by victorraft** [google/ExoPlayer#4140]
I noticed some weird behavior in the streams that have multiple sequential ads in the midroll (those sample tags with `mid-roll standard/optimized pod with 3 ads` for example).
When I minimize the demo app right when the midroll starts playing and then put the app back in foreground the player doesn't seem to recover correctly. 
Sometimes it waits for midroll 1/3 to finish, then skips 2/3 and go straight to 3/3 and stop showing the label that should read `Ad 3 of 3`. Sometimes it freezes on midroll 3/3 and never resumes. When the midroll finishes the content video resumes playback but you can never see the playback control bar again when you click the screen. 
I seem to be getting a random combination of the possibilities above each time I try it.

I was testing this because we received reports that similar issues happened in our app when pressing `Skip Ad` in a midroll that has multiple ads. It is very hard to find adtags with skippable midrolls, though, so I'm having issues reproducing it. Do you think it could be the same issue?

### Reproduction steps
Use the **demo app, version 2.7.3**. 
Go to `IMA Sample ad tags` and pick `VMAP pre-roll single ad, mid-roll standard pod with 3 ads, post-roll single ad` (can be any adtag that has `mid-roll pod with 3 ads`).
Wait for the preroll to finish.
Skip to somewhere around the middle of the video (any part that's after the midroll yellow mark).
As soon as midroll 1/3 starts playing press home to minimize the app.
Open the app again and wait for the playback to resume.  

### Device(s) and version(s) of Android being used
I tested on Android Emulators with android api level 24 and P.

**Comment by andrewlewis** [comment]
We've seen issues with IMA unexpectedly skipping ads in a midroll before, so this may be related.

**Comment by victorraft** [comment]
Is this a priority at the moment? Do you have some sort of idea of when this issue is going to be addressed?
Thanks, @andrewlewis

**Comment by andrewlewis** [comment]
It's possible the issue was addressed in IMA 3.8.5. It would help speed things up if you try to reproduce this on `dev-v2` having set `ImaAdsLoader.DEBUG` to true, and post the logcat captured during a problematic playback.

**Comment by victorraft** [comment]
The issue still happens in `dev-v2`. Here are the logs, starting right before the seek is done and stopping when the last midroll piece is finished: https://gist.github.com/victorraft/1d807593a89a7d51c5195b017d66b058

**Comment by giladna** [comment]
@andrewlewis 

See this thread
https://groups.google.com/forum/#!searchin/ima-sdk/gilad%7Csort:date/ima-sdk/TR2cQQzxCZQ/kV8oEQTWAgAJ

**Comment by andrewlewis** [comment]
[Internal reference: b/78006594]

**Comment by na-in-lee** [comment]
#3764 comment 
[2 ads - just linear vast not vmap midroll]

When the user presses the home button (background) during play first ad, the player automatically paused, user screen turned on (foreground), The player shows only the first ad and goes to the content(without play the second ad)
Ad skins also become skip ad and change 1/2 to 2/2 while the first ad is playing.

Test Ad URL 
- http://api.jtbc.joins.com/ad/now/pre?TYPE=0&CH=ONAIR

**Comment by na-in-lee** [comment]
I Fixed issue.

#4153 apply. then Added code below.

File : ImaAdsLoader.java
 private void handleAdEvent(AdEvent adEvent) {
        Ad ad = adEvent.getAd();

        switch (adEvent.getType()) {
            case LOADED:
                // The ad position is not always accurate when using preloading. See [Internal: b/62613240].
                if(imaPausedContent == true) return;    <--- added code.


[2 ads]
bug: firsts ad play > user skip ad click > contents play
fix : firsts ad play > user skip ad click > second ad play > skip ad click > contents play

**Comment by andrewlewis** [comment]
The IMA team is now investigating what sounds like the same issue. I'll update this if we get more information. Thanks for your patience.

**Comment by OrenMe** [comment]
@andrewlewis can you share a link to tracking bug for the issue if avilable?

**Comment by andrewlewis** [comment]
It's an internal bug but I'll keep this issue updated with anything relevant that comes up.

**Comment by andrewlewis** [comment]
A server-side fix for skipped midroll ads was recently rolled out to the IMA JavaScript code, but unfortunately this still seems to be reproducible. I've filed another issue to follow up (internal: b/110400963).

**Comment by christianb** [comment]
We also have the issue that our midroll ads stopping before they reache the end. 
We are using the ExoPlayer:2.7.1, with Ima-Extension.

**Comment by andrewlewis** [comment]
@christianb Are you seeing that a midroll is skipped when the player is backgrounded while playing a previous midroll in the same ad group? If not it might be different from this issue, so please file a new issue and include the ad tag and steps to reproduce.

**Comment by christianb** [comment]
@andrewlewis We could solve the problem. Was an issue on our side. We removed the Ad view too early. That made the Ad breaking before the end. Now everything works fine :)

**Comment by andrewlewis** [comment]
This is still reproducible with IMA SDK 3.9.4 including in the official IMA sample app, and I think the same issue is occurring with @na-in-lee's ad tag above. I'll post an update here when we have more information about what is going on. [Internal: b/110400963]

**Comment by andrewlewis** [comment]
Note: this is still reproducible using IMA SDK 3.10.2.

**Comment by Maneesh528** [comment]
I am unable to setup Dash Url's and Ima Ads in exoplayer 2.7.3. Can any one help on this

**Comment by andrewlewis** [comment]
Just a quick update: the likely root cause of this has been identified but fixing it is probably going to need to wait until some structural improvements to how preloading works in the IMA SDK have been completed.

**Comment by andrewlewis** [comment]
I've verified this is fixed by migrating to the new IMA SDK preloading APIs (fa7d26dd9f94f52c412ff7d6490630dd73f187a6), and that change should be in a release soon.
