### ISSUE TITLE
Cast extension module missing from jcenter (2.7.1+)

### ISSUE THREAD

**Issue by martinpodkrivacky** [google/ExoPlayer#4142]
Not able to implement extension-cast, any help? I have all updated AS 3.1, etc so it won't be any problem here by my opinion

Failed to resolve: com.google.android.exoplayer:extension-cast:2.7.3
Install Repository and sync project
Show in File
Show in Project Structure dialog

Thanks

**Comment by botaydotcom** [comment]
For some reasons the extension-cast artifacts for new versions (2.7.1, 2.7.2, 2.7.3) are missing from [jcenter.bintray](https://jcenter.bintray.com/com/google/android/exoplayer/extension-cast/), although they are available [here](https://bintray.com/google/exoplayer/extension-cast#files/com/google/android/exoplayer/extension-cast).

**Comment by ojw28** [comment]
I'm following up with Bintray to get this module correctly mirrored into jcenter. Thanks!

**Comment by martinpodkrivacky** [comment]
Thanks

**Comment by ojw28** [comment]
This doesn't appear to be fixed yet?

**Comment by martinpodkrivacky** [comment]
implementation files('src/com/google/android/exoplayer/extension-cast/2.7.3/extension-cast-2.7.3-sources.jar')

**Comment by martinpodkrivacky** [comment]
I fixed it, I just closed issue as I solved it

**Comment by ojw28** [comment]
The more general problem is still there though. You shouldn't need to work around it in the way described. Let's leave it open until the recent versions are correctly included in jcenter.

**Comment by martinpodkrivacky** [comment]
I mean you are right.

**Comment by ojw28** [comment]
This issue has been resolved by Bintray, and all expected versions are now present in jcenter:
https://jcenter.bintray.com/com/google/android/exoplayer/extension-cast/
