### ISSUE TITLE
Seek to a specific point and start playback does not work well with enabling tunnel mode

### ISSUE THREAD

**Issue by rishun-fsi** [google/ExoPlayer#4806]
Hi,
I have tested the demo app by using seek to a specific point and start playback with enabling tunnel mode on some AndroidTV devices, and I encountered some problems.
Please tell me how to resolve the problems.

### Issue description
The details send to dev.exoplayer@gmail.com.

### Reproduction steps
The details send to dev.exoplayer@gmail.com.

### Link to test content
SmoothStreaming / Super speed

### Version of ExoPlayer being used
2.8.4

### Device(s) and version(s) of Android being used
The details send to dev.exoplayer@gmail.com.

Thank you!

**Comment by ojw28** [comment]
We can't help you unless you tell us what the problems actually are.

**Comment by rishun-fsi** [comment]
Below is more information

Test content: SmoothStreaming / Super speed

ExoPlayer 2.8.4

I changed some codes in PlayerActivity class for testing.
I attached the PlayerActivity.java, please check it. 
[PlayerActivity.zip](https://github.com/google/ExoPlayer/files/2377915/PlayerActivity.zip)

Test results:

1. BRAVIA 4K 2015 (Android 7.0)
Always plays well if tunnel mode off.
Most of the time does not play well if tunnel mode on. (first time may work well, but when I press back key then play it again, the playbackState always showing buffering)

2. AQUOS 4TC45AJ1 (Android 8.0.0)
Always plays well if tunnel mode off.
Most of the time does not play well if tunnel mode on. (same as 1.)

3. HUAWEI TT01 (Android 7.0)
Always plays well if tunnel mode off.
Always plays well if tunnel mode on.
				   
Thank you!

**Comment by rishun-fsi** [comment]
Below is new information

I tested the demo app by enabling tunnel mode on. The playbackState never be changed to Player.STATE_ENDED, even though the video current position is over its duration.

Test content: SmoothStreaming / Super speed

ExoPlayer 2.8.4

STATE_ENDED

Test results:

BRAVIA 4K 2015 (Android 7.0)
Not working

AQUOS 4TC45AJ1 (Android 8.0.0)
Not working

HUAWEI TT01 (Android 7.0)
Works well

Thank you!

**Comment by andrewlewis** [comment]
The change in efe8f09f45fe7804e8c92089f744d717502f9019 should fix the issue of not transitioning to the ended state. Please could you try to reproduce using `dev-v2`?

**Comment by rishun-fsi** [comment]
Hi,
Thank you for your prompt response.
I have tested it with efe8f09 change, the ended state problem has been fixed.
But seek to a specific point problem still happens, please check it.

Thank you!

**Comment by rishun-fsi** [comment]
Hi,
Have you reproduced this issue?
I have tested it with the new release ver.2.9.0, it still happens.
Could you help me to fix the problem?
 

Test content: SmoothStreaming / Super speed

ExoPlayer 2.9.0

I changed some codes in PlayerActivity class for testing.
I attached the PlayerActivity.java, please check it.
[PlayerActivity.zip](https://github.com/google/ExoPlayer/files/2427594/PlayerActivity.zip)

Test results:

BRAVIA 4K 2015 (Android 7.0)
Always plays well if tunnel mode off.
Most of the time does not play well if tunnel mode on. (**first time may work well, but when I press back key then play it again, the playbackState always showing buffering**)

Thank you!

**Comment by tonihei** [comment]
@andrewlewis Were you able to reproduce the issue?

**Comment by rishun-fsi** [comment]
Hi,
Currently, I can not tested it with the new release ver.2.10.0.
Because I have not the test device of BRAVIA 4K 2015 (Android 7.0) around me.

**Comment by andrewlewis** [comment]
@rishun-fsi Sorry for the delay. I couldn't reproduce this using the demo app modified to start at a non-zero position and use video tunneling, testing on BRAVIA_ATV3_4K_EU/NRD91N.S133 and SVP4KDTV15_UC/LMY48E.S226. Once you have access to a test device please try to reproduce this again, and if it's still reproducible file a new issue, including a full bug report. Thanks.
