### ISSUE TITLE
Too many NetworkRequests filed

### ISSUE THREAD

**Issue by gongwen** [google/ExoPlayer#5098]
java.lang.IllegalArgumentException
Too many NetworkRequests filed

--detail info
-use version com.google.android.exoplayer:exoplayer:2.8.2
-android version
![image](https://user-images.githubusercontent.com/7523615/48385304-e87cc800-e728-11e8-9059-5efa84f1647c.png)
-Weak network environment

Caused by:
--
5 java.lang.IllegalArgumentException:Too many NetworkRequests filed
6 android.os.Parcel.readException(Parcel.java:1688)
7 android.os.Parcel.readException(Parcel.java:1637)
8 android.net.IConnectivityManager$Stub$Proxy.listenForNetwork(IConnectivityManager.java:2670)
9 android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3519)
10 android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:3738)
11 com.google.android.exoplayer2.scheduler.RequirementsWatcher.registerNetworkCallbackV23(RequirementsWatcher.java:149)
12 com.google.android.exoplayer2.scheduler.RequirementsWatcher.start(RequirementsWatcher.java:95)
13 com.amber.callerlive.player.download.DownloadService$RequirementsHelper.start(DownloadService.java:377)
14 com.amber.callerlive.player.download.DownloadService.onCreate(DownloadService.java:174)
15 android.app.ActivityThread.handleCreateService(ActivityThread.java:3319)
16 android.app.ActivityThread.-wrap5(ActivityThread.java)
17 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
18 android.os.Handler.dispatchMessage(Handler.java:102)
19 android.os.Looper.loop(Looper.java:154)
20 android.app.ActivityThread.main(ActivityThread.java:6349)
21 java.lang.reflect.Method.invoke(Native Method)
22 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
23 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by tonihei** [comment]
That looks to me as if you are starting the DownloadService too often and the system stops accepting the requests at some point. I'd suggest to add a log output to the method to see how often it's called. 

Generally, I don't think this is an exception we should catch because the DownloadService would malfunction without letting you know.

@erdemguven May be able to add more details.

**Comment by gongwen** [comment]
In class DownloadService.RequirementsHelper,Is there such a possibility? When the requirementsNotMet is called, the DownloadService will be started(context.startService). If the DownloadService is not alive at this time, RequirementsHelper.start will be called to add the network listener. At this time, the requirementsNotMet may be called again, forming a loop call, causing such a problem.

**Comment by tonihei** [comment]
@erdemguven Can you take a look?

**Comment by erdemguven** [comment]
This is caused by a bug in 2.8.1 version and fixed in 2.8.2. Please make sure you're using version 2.8.2. Alternatively you might want to upgrade a later version.

**Comment by gongwen** [comment]
The verison of exoplayer that i used is 2.8.2,the problem still exsits.

**Comment by erdemguven** [comment]
In that case, please upgrade to a later version.
