### ISSUE TITLE
ArrayIndexOutOfBoundsException with MP4 videos

### ISSUE THREAD

**Issue by Oleur** [google/ExoPlayer#554]
Hi there, 

I am facing some trouble with my MP4 videos, I am getting an ArrayIndexOutOfBoundsException (length=16; index=16) while loading my mp4 from an URL. Thus, I am not able to play my video.
Here is the complete stack trace from the logcat:

```
E/LoadTask﹕ Unexpected exception loading stream
    java.lang.ArrayIndexOutOfBoundsException: length=16; index=16
            at com.google.android.exoplayer.util.ParsableByteArray.readInt(ParsableByteArray.java:190)
            at com.google.android.exoplayer.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:116)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:235)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:208)
            at com.google.android.exoplayer.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:103)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:616)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
```

I am using the latest dev version of Exoplayer with the Mp4Extractor.
Any explanations about this exception ? 
Thanks a lot

**Comment by ojw28** [comment]
You'll need to provide a sample mp4 for us to debug this. Thanks!

**Comment by Oleur** [comment]
Here is the sample mp4 : https://s3-eu-west-1.amazonaws.com/cinemur-test/test.mp4
If you need more info let me know.
Thanks

**Comment by ojw28** [comment]
Is it possible that this file is fragmented mp4, rather than plain mp4?

**Comment by ojw28** [comment]
@andrewlewis This may or may not be FMP4, but either way parseStbl should probably not crash in the case that sampleCount=0 (as is the case in the sample file). If sampleCount=0 it seems valid that the STSC box can contain entry_count=0. Our code currently assumes that this value is >= 1.

Just returning early from parseStbl if sampleCount=0 resolves the crash, but doesn't allow the media to be played.

**Comment by Oleur** [comment]
It is plain mp4 for sure.

**Comment by andrewlewis** [comment]
The stream contains moof atoms, so it is necessary to use FragmentedMp4Extractor rather than Mp4Extractor. However, we can't play it back even then because it has multiple tracks. Issue #363 tracks adding support for multi-track FMP4 streams.

**Comment by Oleur** [comment]
Using FragmentMp4Extractor gives me this stack trace:
```
E/LoadTask﹕ Unexpected exception loading stream
    java.lang.IllegalStateException: Top bit not zero: -198828144
            at com.google.android.exoplayer.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:240)
            at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:634)
            at com.google.android.exoplayer.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:163)
            at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:616)
            at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
```

So the problem comes from the multiple tracks ?

**Comment by andrewlewis** [comment]
Yes. The extractor is reading an audio sample as if it were a video sample, because it only knows about the video track, and this leads to the exception being thrown.

**Comment by ojw28** [comment]
Closing this as the crash is now fixed, and the feature request to play this type of media is already tracked in #363.

**Comment by elixiroflife4u** [comment]
I encountered a similar array out of bounds index in http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4
that isn't resolved with the patch for this bug (in dev branch). I have updated #363  with more information about it.
