### ISSUE TITLE
Where can I get the GOP (keyframe interval) in DASH streaming.

### ISSUE THREAD

**Issue by AlphaCircle** [google/ExoPlayer#5742]
I want to know the GOP size when I do DASH. When looking at MediaLoadData, I could not find any similar thing to GOP-related information. Can you let me know where I can get that information?

**Comment by ojw28** [comment]
There is no way to get this information. Please can you describe a valid use case for needing this; because I can't really think of one. Note also that there's no requirement that GOP size is fixed in DASH content.

**Comment by AlphaCircle** [comment]
Hello ojw28
Thanks for your quick response.  I did not recognize GOP is not fixed in DASH. I thought one mpeg video with a specific resolution in a specific bandwidth has one GOP size. Thanks for letting me know that. 

I am using 2 instances of exoplayer and wants to, for instance, switch A to B instances when a certain event comes out. But the B instance is necessary to display the same frame as that of A instance when it starts and A gets in Pause state. However, I want to switch A to B on the keyframe only. Keyframe switching is supposed to be faster. As you know, a random frame is built by stacking the previous keyframes and/or anchor frames. But I don't want to lose time but do the switching as quickly as possible. I need foresee where the keyframe is from the current playing position.  So I think GOP would be a good hint to that purpose. 

I used Concatenate MediaSource or Merging MediaSource. Those are wonderful but the moving time from A to B is relatively slow that I expected. 

However, if your saying is correct, that is not good to me. Do you mean the GOP is varying segment by segment? Can you clarify what you intend to say?
