### ISSUE TITLE
Failed to receive STATE_END after calling seekTo() to seek to end of video

### ISSUE THREAD

**Issue by ptran-gpfw** [google/ExoPlayer#596]
We are implementing a kind of loop feature where if the position is at end of video then user can tap play button and position is restored to 0 and playback re-starts from beginning.

However, there is an issue when we call `seekTo( durationMs )` where `durationMs` is the video duration retrieved from `ExoPlayer#getDuration()`. After this call to `seekTo` we rarely get the `onPlayerStateChanged` callback from ExoPlayer. We expect to receive an event for `STATE_END`.

We only observe the event for `STATE_BUFFERING` but rarely get the `STATE_END` event. Rarely meaning 1 out of 10 times we get the expected `STATE_END` event.

This is an issue for use because we need the STATE_END event to let us know we are at the end at should loop and restart playback from beginning.

Another datapoint: we have a workaround where 1 millisecond is subtracted from the `seekTo` value. I.e.,
```
seekTo( durationMs - 1)
```
This workaround is allows us to get expected `STATE_ENDED` event 100% of the time.

(CC: @FranciscoRuiz-gpsw)

**Comment by ptran-gpfw** [comment]
Related (kind of) to #490.

**Comment by ojw28** [comment]
What components are you using to build your player? Specifically, which SampleSource implementation are you using?

**Comment by ptran-gpfw** [comment]
ExtractorSampleSource with Mp4Extractor:
```
        String userAgent = Util.getUserAgent(context, GPHttpUtil.getHeaderUserAgent(context));
        DataSource dataSource = new DefaultUriDataSource(context, userAgent);
        mSampleSource = new ExtractorSampleSource(uri, dataSource, new Mp4Extractor(), 2,
                BUFFER_SIZE);
```

**Comment by andrewlewis** [comment]
I'm investigating an issue where seeking to the end of a stream with ExtractorSampleSource can cause the player to get stuck without transitioning to STATE_ENDED. The extractor immediately signals that the end of the stream has been reached, but the last buffer from the audio decoder contains media that is never played, so the player never sees the end of the stream. This may be specific to MP3.

**Comment by brianchu** [comment]
It also happens to HLS file when the video is actually shorter (or longer) than reported or the m3u file doesn't have TARGETDURATION

**Comment by ojw28** [comment]
This should be fixed on dev.

**Comment by Kening** [comment]
I am using the latest code from master (tag r1.4.2), still see this problem with HLS. I do have target duration set properly in the playlist.

#EXT-X-TARGETDURATION:10

This happens kinda random, but normally happens on a longer video after seeking, the STATE_ENDED state is not trigger on onPlayerStateChanged() .

**Comment by Kening** [comment]
I am debugging, and see something like this which may be a hint:

in ExoPlayerImplInternal.java the method doSomeWork(), there are code that's checking if all the enabledRenderers are ended. When I see the problem, I see that my video renderer is ended, but the audio renderer and text renderer is not.

And if I dig in to MediaCodecAudioTrackRenderer, I can see its outputStreamEnded is false, and if I dig into TextTrackRenderer, I can see its inputStreamEnded is false.

**Comment by Kening** [comment]
this may be a bug in my SampleSource code, I have a customized SampleSource class that's loading a subtitle file. If I don't have that TextRenderer (which is for the subtitle), then I don't see this problem.
