### ISSUE TITLE
Playing MP4 video file sometimes don't see STATE_ENDED event

### ISSUE THREAD

**Issue by brian-chu-twc** [google/ExoPlayer#707]
Condition:
Add this mp4 video (it's DFP pre-roll ad demo video) playing in Exoplayer demo:
<pre><code>
 public static final Sample[] MISC = new Sample[] {
                    new Sample("ISSUE 707 END_EVENT?", "https://s3-us-west-2.amazonaws.com/test.twc/dfp.mp4",
                  PlayerActivity.TYPE_OTHER),
...
</code></pre>

You can find the source code changes in https://github.com/brian-chu-twc/ExoPlayer/tree/ExoPlayer-707 </br></br>

Observation:
Let it play all to the end, it works, saw playbackState from ready to 'ended'.
However, when you drag the control almost to the end (~ 1 second before the end), it got stucked in the state:
<pre>
playWhenReady=true, playbackState=ready
</pre>

and never proceed to the very end of the video.

The other way to reproduce is the click the Pause button (~ 1 second before the end), same result.

See the video of this issue: https://s3-us-west-2.amazonaws.com/test.twc/screen-recording_20150812-114312.mp4

Device:
Samsung S4, S5, HTC M8.

Suspect:
possible related to issue #596

**Comment by Kening** [comment]
I am debugging, and see something like this which may be a hint:

in ExoPlayerImplInternal.java the method doSomeWork(), there are code that's checking if all the enabledRenderers are ended. When I see the problem, I see that my video renderer is ended, but the audio renderer and text renderer is not.

And if I dig in to MediaCodecAudioTrackRenderer, I can see its outputStreamEnded is false, and if I dig into TextTrackRenderer, I can see its inputStreamEnded is false.

I thought this may be a bug in my SampleSource code, since I have a customized SampleSource class that's loading a out-of-band subtitle file. If I don't have that TextRenderer (which is for the subtitle), then I don't see this STATE_ENDED missing problem.

Then I see issue #587 is recommending a solution like this:

DataSource textDataSource = new DefaultUriDataSource(context, bandwidthMeter, userAgent);
SingleSampleSource textSampleSource = new SingleSampleSource(textUri, textDataSource,
MediaFormat.createTextFormat(MimeTypes.APPLICATION_SUBRIP, C.MATCH_LONGEST_US));
TrackRenderer textRenderer = new TextTrackRenderer(textSampleSource, player,
player.getMainHandler().getLooper());

I am using TTML, so I use this new approach with jut the MIME type updated to MimeTypes.APPLICATION_TTML, and I also know the duration in micro-seconds, so I use the exact duration instead of C.MATCH_LONGEST_US. This is more elegant than my customized SampleSource (which is using an AsyncTask to load the subtitle file), the subtitle works, but it doesn't solve the STATE_ENDED missing problem. I still see that the TextRenderer is not "ended" even though the video renderer is already ended (in the doSomeWork() call).

**Comment by Kening** [comment]
I think the problem is that when the video is ended, the player will stopRenderers(), and all enabled renderers' states are going to change from STATE_STARTED to STATE_ENABLED. 

For the video render and audio render, even though they are no longer in the STATE_STARTED state, their parent class MediaCodecTrackRenderer will properly call doSomeWork()->drainOutputBuffer()->processEndOfStream()->set outputStreamEnded=true, which will return isEnded()==true.

For the text renderer, TextTrackRender's doSomeWork() is checking whether the state of the renderer is STATE_STARTED, if it's not, it's not going to do any work and not going to set inputStreamEnded to true, which cause isEnded()==false.

We will need some fix in the TextTrackRenderer's doSomeWork(), to make sure when the state is not STARTED, we will still properly update inputStreamEnded.

**Comment by Kening** [comment]
ah, that stopRenderers() call is actually triggered by my code, I am tracking the progress of the video playback (in order to send some metrics call) using a handler, keep posting sendMessageDelayed. If I notice the position is >= duration, I fire off a pause, which trigger setPlayWhenReady(false), which triggers stopRenderers(). So this is not related.

I remove that call, and now the thing is this: I am using a SingleSampleSource to load the out-of-band subtitle file (base on suggestion in #587). When video and audio track renderers are all ended, the text track renderer is not because in TextTrackRenderer's doSomeWork(), it's trying to read data from its SampleSourceReader, which is the SingleSampleSource object, and this call always return SAMPLE_READ, so inputStreamEnded is never set to true. 

I need to have a better understanding what SingleSampleSource is doing. Maybe we need a fix here.

**Comment by ojw28** [comment]
The issue appears to be with the audio track, specifically with the use of [hasEnoughDataToBeginPlayback](https://github.com/google/ExoPlayer/blob/master/library/src/main/java/com/google/android/exoplayer/MediaCodecAudioTrackRenderer.java#L212). In the case of seeking very close to the end of the video, we only have a small amount of audio that we can play.

We think we have enough audio to start playback, so we say that the track hasn't ended and try and play it. Unfortunately, the underlying AudioTrack doesn't actually play anything, presumably because it doesn't think it has enough data to start playing, so we end up in a state where we're waiting for the AudioTrack to play out the data that we've fed it, but the AudioTrack is waiting for us to feed more data.

I don't think there's a particularly clean solution to this; we'll probably need to implement a fairly hacky workaround to transition directly to STATE_ENDED for this case.

**Comment by ojw28** [comment]
This should be fixed now. Thanks!

**Comment by brian-chu-twc** [comment]
I tried demo on dev branch on Galaxy S6, version 5.0.2. still seeing the issue: using the pause and resume button actually works good near the end, but dragging the controller near the end still can result in a state which playWhenReady=true, playbackState=ready and not playing.

**Comment by darussian** [comment]
I am also experiencing this issue playing HLS streams using Exoplayer r1.4.2. If I scrub to the end of the stream  ExoPlayer.STATE_ENDED is never called, if i let the stream end normally the callback is fired correctly.

**Comment by ojw28** [comment]
We made several fixes in 1.5.0 to address this issue. I'm going to close this, because it's probably fixed. Please let us know if you're still able to reproduce, providing all of the relevant information described [here](https://google.github.io/ExoPlayer/2015/10/01/reporting-issues.html). It would probably be best to report as a new issue if so. Thanks!

**Comment by ojw28** [comment]
Note - The specific change that probably addressed this issue is https://github.com/google/ExoPlayer/commit/e8895c8746487351ededbe0dd072f3fb31468c75.

**Comment by darussian** [comment]
Thanks, Ill check it out
