### ISSUE TITLE
Exo ImaAdsLoader does not consider media load timeout

### ISSUE THREAD

**Issue by Oziomajnr** [google/ExoPlayer#7846]
### [REQUIRED] Issue description
When I set the media load time out on the Ima Ads loader, it does not time out when the request for ad media takes longer than the set time out instead it just doesn't load the add and does not throw any error. I am supposed to get an  `AdError.AdErrorCode.VAST_MEDIA_LOAD_TIMEOUT` on the ad error listener that I have attached to the AdsLoader. This is not the case for the VAST_LOAD_TIMEOUT, when I set the same value for the Vast load timeout, I get the `AdError.AdErrorCode.VAST_LOAD_TIMEOUT` correctly.

Here is a snippet of how I set the time out

```
val adsLoader = adsLoader ?: ImaAdsLoader.Builder(context).apply {
                                this.setImaSdkSettings(imaSdkSettings)
                                this.setAdEventListener(imaAdEventListener)
                                this.setMediaLoadTimeoutMs(2000)
                            }.buildForAdTag(Uri.parse(mediaAsset.advertTag)).apply {
                                adsLoader.addAdErrorListener(imaAdErrorListener)
                            }
```

### [REQUIRED] Reproduction steps
1. Set the MediaLoadTimeoutMs on the Exo player's ImaAdsLoader to a very low value, e.g 1000ms
Throttle the request for ads media using a proxy or any other means, I use Charles proxy and delay requests for the following URLs 
1. r1---sn-5hne6ns6.gvt1.com
2. redirector.gvt1.com

The AD media loads for some 8 seconds and then it skips AD without throwing any error.

### [REQUIRED] Link to test content
Sample VAST TAG
"https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostlongpod&cmsid=496&vid=short_tencue&correlator="

### [REQUIRED] Version of ExoPlayer being used
Exo Player Version: 2.11.7
IMA extension version: 2.11.7

### [REQUIRED] Device(s) and version(s) of Android being used
Techno Camom CX Air, Android 7.0
Samsung Galaxy S10 Emulato, Android 10

**Comment by christosts** [comment]
@andrewlewis can you take a look?

**Comment by andrewlewis** [comment]
Please could you try with 2.11.8? I think this was fixed in c0cd73f5fd983c2f5bea9ff090d23aef3e09d965.

**Comment by andrewlewis** [comment]
Likely the same as #7170.

**Comment by Oziomajnr** [comment]
I just tried with 2.11.8 and it's still an issue. AdError.AdErrorCode.VAST_MEDIA_LOAD_TIMEOUT is still not thrown after a timeout and the player skips the ads after some time.

**Comment by andrewlewis** [comment]
Hm, setting a timeout works for me in the demo app on the development branch, which should work the same. If I set a 1 ms media load timeout, all ad breaks time out.

Are you seeing this behavior with both preroll and midrolls? I wonder whether the delay introduced by the proxy is not sufficient to cause a timeout on midrolls because the ads actually load several seconds before the corresponding ad break. Please could you try setting `ImaAdsLoader.DEBUG = true`, reproducing the issue and then attaching the output logcat?

**Comment by Oziomajnr** [comment]
Thank you, after setting ImaAdsLoader.DEBUG = true I can see that it is actually being thrown on v2.11.8, and I have attached the logs below. However, I cannot detect when this error is thrown so that I can take appropriate actions, the Ad Error listener that I had added above through
  
        `  adsLoader.adsLoader.addAdErrorListener(imaAdErrorListener)`

 Is attached to the Google ImaAdsLoader, not the Exo ImaAdsLoader, the `AdError.AdErrorCode.VAST_MEDIA_LOAD_TIMEOUT ` is not reported to that listener while `AdError.AdErrorCode.VAST_LOAD_TIMEOUT` is reported correctly. Here is my implementation of the error listener.

```
internal class AdErrorListener(private val analyticsEventListener: AnalyticsEventListener) :
    AdErrorEvent.AdErrorListener {
    override fun onAdError(adErrorEvent: AdErrorEvent) {
        analyticsEventListener.onEvent(Event.AdError(adErrorEvent.error.toString()))
        when (adErrorEvent.error.errorCode) {
            AdError.AdErrorCode.VAST_LOAD_TIMEOUT -> {
                analyticsEventListener.onEvent(Event.AdTimeout())
            }
            AdError.AdErrorCode.VAST_MEDIA_LOAD_TIMEOUT -> {
                analyticsEventListener.onEvent(Event.AdTimeout())
            }
            else -> {
                Log.d(this::class.java.name, " Ad error code $adErrorEvent.error.errorCode")
            }
        }
    }
}
```

Here is the log output after setting  ImaAdsLoader.DEBUG = true.

```
2020-09-09 21:20:51.576 29090-29090/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=1.81, mediaPos=0.00, window=0, loadError
      com.google.android.exoplayer2.source.ads.AdsMediaSource$AdLoadException: AdError [errorType: PLAY, errorCode: AdErrorCode [name: VAST_MEDIA_LOAD_TIMEOUT, number: 402], message: VAST media file loading reached a timeout of 0.001 seconds.]
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader$ComponentListener.onAdError(ImaAdsLoader.java:1444)
        at com.google.ads.interactivemedia.v3.internal.ajv.a(IMASDK:5)
        at com.google.ads.interactivemedia.v3.internal.ajo.a(IMASDK:30)
        at com.google.ads.interactivemedia.v3.internal.ajo.b(IMASDK:57)
        at com.google.ads.interactivemedia.v3.internal.ajo.a(IMASDK:54)
        at com.google.ads.interactivemedia.v3.internal.akl.a(IMASDK:83)
        at com.google.ads.interactivemedia.v3.internal.ako.b(IMASDK:20)
        at com.google.ads.interactivemedia.v3.internal.akm.shouldOverrideUrlLoading(IMASDK:6)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-Monochrome.aab-stable-418308173:16)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:328)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:6289)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
     Caused by: AdError [errorType: PLAY, errorCode: AdErrorCode [name: VAST_MEDIA_LOAD_TIMEOUT, number: 402], message: VAST media file loading reached a timeout of 0.001 seconds.]
        at com.google.ads.interactivemedia.v3.internal.ajo.a(IMASDK:53)
        at com.google.ads.interactivemedia.v3.internal.akl.a(IMASDK:83) 
        at com.google.ads.interactivemedia.v3.internal.ako.b(IMASDK:20) 
        at com.google.ads.interactivemedia.v3.internal.akm.shouldOverrideUrlLoading(IMASDK:6) 
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73) 
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-Monochrome.aab-stable-418308173:16) 
        at android.os.MessageQueue.nativePollOnce(Native Method) 
        at android.os.MessageQueue.next(MessageQueue.java:328) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:6289) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955) 
    ]
2020-09-09 21:22:50.514 29090-1901/com.google.android.exoplayer2.demo E/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] storeMetaDataInBuffers failed w/ err -1010
2020-09-09 21:22:50.703 29090-1907/com.google.android.exoplayer2.demo E/ACodec: cannot find aac bit rate
2020-09-09 21:23:48.583 29090-29090/com.google.android.exoplayer2.demo E/EventLogger: internalError [eventTime=61.52, mediaPos=0.00, window=0, loadError
      com.google.android.exoplayer2.source.ads.AdsMediaSource$AdLoadException: AdError [errorType: PLAY, errorCode: AdErrorCode [name: VAST_MEDIA_LOAD_TIMEOUT, number: 402], message: VAST media file loading reached a timeout of 0.001 seconds.]
        at com.google.android.exoplayer2.ext.ima.ImaAdsLoader$ComponentListener.onAdError(ImaAdsLoader.java:1444)
        at com.google.ads.interactivemedia.v3.internal.ajv.a(IMASDK:5)
        at com.google.ads.interactivemedia.v3.internal.ajo.a(IMASDK:30)
        at com.google.ads.interactivemedia.v3.internal.ajo.b(IMASDK:57)
        at com.google.ads.interactivemedia.v3.internal.ajo.a(IMASDK:54)
        at com.google.ads.interactivemedia.v3.internal.akl.a(IMASDK:83)
        at com.google.ads.interactivemedia.v3.internal.ako.b(IMASDK:20)
        at com.google.ads.interactivemedia.v3.internal.akm.shouldOverrideUrlLoading(IMASDK:6)
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-Monochrome.aab-stable-418308173:16)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:328)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:6289)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
     Caused by: AdError [errorType: PLAY, errorCode: AdErrorCode [name: VAST_MEDIA_LOAD_TIMEOUT, number: 402], message: VAST media file loading reached a timeout of 0.001 seconds.]
        at com.google.ads.interactivemedia.v3.internal.ajo.a(IMASDK:53)
        at com.google.ads.interactivemedia.v3.internal.akl.a(IMASDK:83) 
        at com.google.ads.interactivemedia.v3.internal.ako.b(IMASDK:20) 
        at com.google.ads.interactivemedia.v3.internal.akm.shouldOverrideUrlLoading(IMASDK:6) 
        at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73) 
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-Monochrome.aab-stable-418308173:16) 
        at android.os.MessageQueue.nativePollOnce(Native Method) 
        at android.os.MessageQueue.next(MessageQueue.java:328) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:6289) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955) 
    ]
2020-09-09 21:28:50.515 29090-29102/com.google.android.exoplayer2.demo E/System: Uncaught exception thrown by finalizer
2020-09-09 21:28:50.529 29090-29102/com.google.android.exoplayer2.demo E/System: java.lang.IllegalStateException: Binder has been finalized!
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:622)
        at com.android.internal.app.IAppOpsService$Stub$Proxy.stopWatchingMode(IAppOpsService.java:435)
        at android.media.PlayerBase.baseRelease(PlayerBase.java:136)
        at android.media.AudioTrack.finalize(AudioTrack.java:979)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:223)
        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:210)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by Oziomajnr** [comment]
Update: This is most likely an issue with the Google IMA ads loader, after analyzing the logs, I figured out it is reporting the Media load time out as an `AdEvent` of type `LOG` event so checking for the log event and the ads type I was able to determine when the media time out is thrown like this.

 ```
override fun onAdEvent(event: AdEvent?) {
            AdEvent.AdEventType.LOG -> {
                if (event.adData["type"] == "adPlayError" && event.adData["errorCode"] == "402") {
                    analyticsEventListener.onEvent(Event.AdTimeout())
                }
            }
    }
```

I am not sure if this is how it should work or if other events could have these properties, but it works for me for now.

**Comment by andrewlewis** [comment]
I've mentioned this to the IMA SDK team in case it's not working as intended. Closing as the original problem seems to be addressed.
