### ISSUE TITLE
Exoplayer does not complete playback when postroll ad tag is returning empty vast

### ISSUE THREAD

**Issue by krackjack234** [google/ExoPlayer#8431]
We are seeing a problem with Exoplayer 2.12.0 where the player is getting stuck and not reporting STATE_ENDED event when the postroll ad tag returns empty vast

We haved shared the sample Exoplayer test app with client ad tag privately to dev.exoplayer@gmail.com

In the Exoplayer demo app we can see the problem by using the following steps:

_Try the option IMA sample ad tags- > Single inline linear to see the issue. You will notice that on reaching the end of playback, the sample player goes into buffering and doesnot report end of playback_
 

- ExoPlayer version number: 2.12.0
- Android version: All
- Android device: All

**Comment by krackjack234** [comment]
Hi @andrewlewis, did you get a chance to look into this?

**Comment by andrewlewis** [comment]
In the ExoPlayer demo app on `dev-v2` the ad tag provided via email plays to the end and the player transitions to `STATE_ENDED`, but the postroll ad was not empty.

Please could you check whether this issue reproduces for you using `dev-v2` preferably in the ExoPlayer demo app, and, if so, supply the logs output when reproducing the error, with debug logs enabled via`ImaAdsLoader.Builder.setDebugModeEnabled(true)` when building the `ImaAdsLoader`? Please send the logs via email to `dev.exoplayer@gmail.com` with subject line 'Issue #8431' and reply here once you've done that so we can take a look. Thanks.

**Comment by andrewlewis** [comment]
For what it's worth, I also tested with [this test ad tag](https://vastsynthesizer.appspot.com/full-midroll-empty-postroll), which has a midroll and an empty postroll, and playback ended as expected.

**Comment by krackjack234** [comment]
hi @andrewlewis  we have shared a new ad tag over mail where we could reproduce the issue. The issue seems to happen when we seek over midroll cue points and both the midroll and postroll return empty vast. Issue is seen after IMAAdsLoader reports a LOG and then an AD_BREAK_FETCH error event.

We have also shared IMA logs for this scenario.

Do let us know if you want us to check in any of the dev releases.

Thanks

**Comment by andrewlewis** [comment]
I tried using the new ad tag provided via email but I didn't see any empty ad breaks and couldn't reproduce the issue.

I suspect you may be seeing the same bug as #8205, which was fixed in 2.12.3. Please could you try that release?

**Comment by krackjack234** [comment]
Hi @andrewlewis , we checked the same ad tag with Exoplayer v2.12.3 but we still see the issue. 
We have shared the attached logs over mail. We dont see any STATE_ENDED event coming if we scrub across multiple cuepoints where all cuepoints returns empty vast.

**Comment by andrewlewis** [comment]
It looks like the ad tag has cue points after the duration of the content (there is a cue point at one hour, but the emailed logs show a duration of about 20 minutes). I'm afraid this is currently not supported. See #5534 for more information.

**Comment by andrewlewis** [comment]
Duplicate of #5534
