### ISSUE TITLE
PIP flickering

### ISSUE THREAD

**Issue by MrTommy94** [google/ExoPlayer#8611]
Hi, 
I'm implementing PIP feature following the android developer guide.
When animating I'm using a `SurfaceView` (I can't use a `TextureView` because I can't play HDR videos).
When I am in pip mode and i tap on the pip window in order to show the control player i notice a flickering: the SurfaceView has a strange behavior as shown below: 

![2021-02-19 17 10 00](https://user-images.githubusercontent.com/30128519/108530503-f5a89a00-72d5-11eb-9e92-cebd816a0d3c.jpg)
![2021-02-19 17 10 10](https://user-images.githubusercontent.com/30128519/108530519-f93c2100-72d5-11eb-9a36-82db7b8c0fbb.jpg)

You can reproduce the same problem updating the Exoplayer demo project:
here you can find the `git diff` 

```
diff --git a/demos/main/src/main/AndroidManifest.xml b/demos/main/src/main/AndroidManifest.xml
index 053665502..2c36edab7 100644
--- a/demos/main/src/main/AndroidManifest.xml
+++ b/demos/main/src/main/AndroidManifest.xml
@@ -65,6 +65,7 @@
         android:configChanges="keyboard|keyboardHidden|orientation|screenSize|screenLayout|smallestScreenSize|uiMode"
         android:launchMode="singleTop"
         android:label="@string/application_name"
+        android:supportsPictureInPicture="true"
         android:theme="@style/PlayerTheme">
       <intent-filter>
         <action android:name="com.google.android.exoplayer.demo.action.VIEW"/>
diff --git a/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java b/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java
index 5fb342be4..1da9a3634 100644
--- a/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java
+++ b/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java
@@ -19,6 +19,7 @@ import static com.google.android.exoplayer2.util.Assertions.checkNotNull;
 
 import android.content.Intent;
 import android.content.pm.PackageManager;
+import android.os.Build;
 import android.os.Bundle;
 import android.util.Pair;
 import android.view.KeyEvent;
@@ -105,6 +106,10 @@ public class PlayerActivity extends AppCompatActivity
     setContentView();
     debugRootView = findViewById(R.id.controls_root);
     debugTextView = findViewById(R.id.debug_text_view);
+
+    debugRootView.setVisibility(View.GONE);
+    debugTextView.setVisibility(View.GONE);
+
     selectTracksButton = findViewById(R.id.select_tracks_button);
     selectTracksButton.setOnClickListener(this);
 
@@ -160,11 +165,8 @@ public class PlayerActivity extends AppCompatActivity
   @Override
   public void onPause() {
     super.onPause();
-    if (Util.SDK_INT <= 23) {
-      if (playerView != null) {
-        playerView.onPause();
-      }
-      releasePlayer();
+    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
+      enterPictureInPictureMode();
     }
   }
```
 

Android version: all android versions that support pip feature (from Android 24)
Tested on many different devices (Samsung Galaxy S20+, Samsung Galaxy S9, Pixel 3, Nexus 6 ecc...)
Exoplayer version: 2.13.1

**Comment by ojw28** [comment]
Thanks for the clear reproduction steps. I was able to apply your patch to enable PIP mode. It doesn't reproduce across all devices for me though. I suspect that it's an issue that has been fixed in a recent Android release. Either Android 11 or Android 10 based on the data points below. If you have a data point for Android 10 then that would be helpful, to fill in the gap.

* S8 - Android 9 - Reproduces
* S20 - Android 11 - Cannot reproduce
* Pixel 5 - Internal Dev Build - Cannot reproduce

On the S8, I found that adding the following two lines of code to `PlayerActivity.onCreate` removed the flicker . The PIP resize animation still doesn't look totally smooth, but the most jarring flickering is definitely gone.

```
SurfaceView surfaceView = (SurfaceView) playerView.getVideoSurfaceView();
surfaceView.getHolder().setFixedSize(1, 1);
```

Do you also observe that (a) the issue doesn't affect Android 11 (and possibly Android 10, to be determined), and (b) on affected devices, and (b) the workaround resolves the problem? If so, then:

* You can probably use this as a workaround, unless you observe any negative effects.
* I can follow up with the relevant platform team to try and understand why this helps, and if/when it was fixed in the platform. I'd also like to understand whether there are any downsides of the workaround, and if using the made up `(w=1, h=1)` dimensions rather than the actual video resolution is problematic at all.
* We should consider whether we want to call `setFixedSize` by default in `PlayerView` and `StyledPlayerView` on versions of Android that are affected by the issue. Getting a better understanding of the root cause and workaround is probably a prerequisite to deciding this.

**Comment by MrTommy94** [comment]
Thank you for your support.
I tried your workaround and for the moment it seems to works great without any kind of side effects. 
It seems to work for every device (brand and Android version). I will update you if i find some problems.
Thanks again.

**Comment by MrTommy94** [comment]
Hi, 
after a session of tests on different devices we noticed that the problem is still present on some devices.

Devices: 
- Xiaomi 9T, miui 12, Android 10
- Pixel 3 XL API 29 (Emulated)

Git diff:
```
diff --git a/demos/main/src/main/AndroidManifest.xml b/demos/main/src/main/AndroidManifest.xml
index 053665502..2c36edab7 100644
--- a/demos/main/src/main/AndroidManifest.xml
+++ b/demos/main/src/main/AndroidManifest.xml
@@ -65,6 +65,7 @@
         android:configChanges="keyboard|keyboardHidden|orientation|screenSize|screenLayout|smallestScreenSize|uiMode"
         android:launchMode="singleTop"
         android:label="@string/application_name"
+        android:supportsPictureInPicture="true"
         android:theme="@style/PlayerTheme">
       <intent-filter>
         <action android:name="com.google.android.exoplayer.demo.action.VIEW"/>
diff --git a/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java b/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java
index 5fb342be4..722d8789b 100644
--- a/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java
+++ b/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java
@@ -19,9 +19,11 @@ import static com.google.android.exoplayer2.util.Assertions.checkNotNull;
 
 import android.content.Intent;
 import android.content.pm.PackageManager;
+import android.os.Build;
 import android.os.Bundle;
 import android.util.Pair;
 import android.view.KeyEvent;
+import android.view.SurfaceView;
 import android.view.View;
 import android.view.View.OnClickListener;
 import android.widget.Button;
@@ -105,6 +107,10 @@ public class PlayerActivity extends AppCompatActivity
     setContentView();
     debugRootView = findViewById(R.id.controls_root);
     debugTextView = findViewById(R.id.debug_text_view);
+
+    debugRootView.setVisibility(View.GONE);
+    debugTextView.setVisibility(View.GONE);
+
     selectTracksButton = findViewById(R.id.select_tracks_button);
     selectTracksButton.setOnClickListener(this);
 
@@ -112,6 +118,11 @@ public class PlayerActivity extends AppCompatActivity
     playerView.setControllerVisibilityListener(this);
     playerView.setErrorMessageProvider(new PlayerErrorMessageProvider());
     playerView.requestFocus();
+    if (playerView.getVideoSurfaceView() != null) {
+      SurfaceView surfaceView = (SurfaceView) playerView.getVideoSurfaceView();
+      surfaceView.getHolder().setFixedSize(1, 1);
+    }
+
 
     if (savedInstanceState != null) {
       trackSelectorParameters = savedInstanceState.getParcelable(KEY_TRACK_SELECTOR_PARAMETERS);
@@ -160,11 +171,8 @@ public class PlayerActivity extends AppCompatActivity
   @Override
   public void onPause() {
     super.onPause();
-    if (Util.SDK_INT <= 23) {
-      if (playerView != null) {
-        playerView.onPause();
-      }
-      releasePlayer();
+    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
+      enterPictureInPictureMode();
     }
   }
 

```


https://user-images.githubusercontent.com/30128519/108824648-4106c500-75c2-11eb-8e8d-07570ec8dc3e.mov

**Comment by moneytoo** [comment]
When I use `setFixedSize()`, it gets rid of the (occasional) flickering when switching to (or interacting with) PiP for me (OnePlus 7 running Android 10).

> I'd also like to understand whether there are any downsides of the workaround, and if using the made up (w=1, h=1) dimensions rather than the actual video resolution is problematic at all.

Made up values like this break aspect ratio in `AspectRatioFrameLayout.RESIZE_MODE_ZOOM`. (It works fine with the actual video size in `setFixedSize()`.)

**Comment by ojw28** [comment]
> after a session of tests on different devices we noticed that the problem is still present on some devices.

I doubt there is much we can do for these devices, if the workaround doesn't work.

I will leave this open for us to consider whether we want to enable a `setFixedSize` workaround by default, taking into account the comment above about it not working correctly unless real dimensions are used when in `RESIZE_MODE_ZOOM`.
