### ISSUE TITLE
Rotation issue

### ISSUE THREAD

**Issue by emakovsky** [google/ExoPlayer#91]
1) record a video in portrait using native android camcorder (nexus 4)
2) play it using native player. Rotation is correct
3) play it using demo app (SimplePlayerActivity). Video is rotated.

Example of the test video:
https://drive.google.com/file/d/0B9_5dr6in8cWcmlGZlJrSlhHS1U/view?usp=sharing

Metadata of the mp4 contains a property:
Rotation                       : 90°
but it's ignored by the exo player.

**Comment by IanDBird** [comment]
We're also having issues with this lack of functionality.

**Comment by andrejvanderzee** [comment]
Same problem here.

**Comment by andrejvanderzee** [comment]
Any plans on fixing this?

**Comment by ryango** [comment]
I would argue this is a MediaCodec/libstagefright bug not an ExoPlayer bug as MediaCodec is what's doing the rendering. ExoPlayer is just managing the samples and timing. Also this is evident in the Lollipop libstagefright fix in which it respects the rotation (which screws things up for my use and I had to add this to counteract it)
```
            MediaFormat format = extractor.getTrackFormat(trackIndex);
            if (format.containsKey("rotation-degrees")) {
                // Decoded video is rotated automatically in Android 5.0 lollipop.
                // refer: https://android.googlesource.com/platform/frameworks/av/+blame/lollipop-release/media/libstagefright/Utils.cpp
                format.setInteger("rotation-degrees", 0);
            }
```

**Comment by IanDBird** [comment]
Has anyone seen whether it's still an issue if you're using the MP4 support currently in development? It's currently available on the `dev` branch here (https://github.com/google/ExoPlayer/blob/dev/demo/src/main/java/com/google/android/exoplayer/demo/player/Mp4RendererBuilder.java#L35). Arguably, that's one of the benefits of adding MP4 support into ExoPlayer rather than relying on the MediaCodec/libstagefright support.

**Comment by ojw28** [comment]
Pulling the extractor up to ExoPlayer wont fix the issue, because the issue is in the decoder (not being pulled up) not the extractor (being pulled up).

**Comment by andrejvanderzee** [comment]
So what would be the recommended way to solve this? The TextureView instead of SurfaceView approach like Inikilla kindly posted?

**Comment by Ood-Tsen** [comment]
Hi @IanDBird @ryango 
You may check my quick update [parse mp4 rotation degree](https://github.com/Ood-Tsen/ExoPlayer/commit/a86939dc2ce86eb25b632fb97e484c395a8361af)

"rotation-degrees" is defined in the [ACodec](https://android.googlesource.com/platform/frameworks/av/+/android-5.0.1_r1/media/libstagefright/ACodec.cpp), but it's hidden.
we cannot guarantee it still available in the future.

**Comment by Ood-Tsen** [comment]
This is another update for [rotate by demo app ](https://github.com/Ood-Tsen/ExoPlayer/commit/c5a67f80c8a02151500bb31ff62585997f43ca9b)

**Comment by ojw28** [comment]
The behavior has been fixed as far as is possible in the change above.

Background: The underlying platform changed in Lollypop to start automatically applying rotation when decoding video into a surface. Prior to Lollypop the rotation was not applied. Since it's not possible to perform the rotation at the application level when using SurfaceView, the Lollypop+ behavior is the correct long term solution.

Solution: After the change above, on Lollypop+ the rotation will always be applied correctly. On earlier versions of Android the rotation will not be applied, however the player will now report the unapplied rotation through the MediaCodecVideoTrackRenderer listener:

https://github.com/google/ExoPlayer/blob/d3995eaa7ad2e8406c1c86f3035f31d762352baf/library/src/main/java/com/google/android/exoplayer/MediaCodecVideoTrackRenderer.java#L74

This allows an application using TextureView to easily apply the rotation by making the appropriate call to  TextureView.setTransform. Note that on Lollypop+ unappliedRotationDegrees will always be equal to 0.

**Comment by Ood-Tsen** [comment]
Thanks @ojw28 , you complete the solution.

**Comment by Shusshu** [comment]
Is there a snapshot/dev repo to test this quickly in our app? or when will it get released ?

**Comment by ojw28** [comment]
You can get the latest source from the [dev](https://github.com/google/ExoPlayer/tree/dev) branch and build it yourself (or include the source directly in your project). We don't provide jar/aar binaries prior to release.

Note that the APIs (in general - nothing specific to rotation) are a little unstable on the dev brach due to the arrival of multi-track support, so if you go down this route please be aware that they may change again before the next release.

**Comment by Shusshu** [comment]
From dev I had other issues so finally I cherry-picked the changes + had to do extra changes that I took from dev to make it work:
If anyone needs it: https://github.com/Shusshu/ExoPlayer/tree/142-rotation

**Comment by dnutcracker** [comment]
@ojw28 Just a small remark - the automatic applying of video orientation while decoding to a surface is true only for the default hardware decoder - when using software decoding for example (using OMX.google.h264.decoder) it does not apply rotation even on Lollipop+.
So for people using custom decoders (software or other) might still need the orientation parameter even on Lollipop+ (So maybe the orientation param should always be included and ignored on Lollipopo+?)

**Comment by ojw28** [comment]
Urgh, this is a bit of a mess at the platform level. Application of rotation is inconsistent between both API levels (pre-L v.s. L+) and (in L at least) between decoders at a fixed API level. It appears that on M+ OMX.google.h264.decoder does actually apply the rotation, but you're correct in noting that this does not happen when running L.

Unfortunately, as of now, there's no easy way to determine whether a decoder has actually applied the rotation. I'm not sure how consistent the application of rotation is between decoders in M. I'll be pushing for more consistent application of rotation (if this hasn't happened already) and/or the ability to determine whether the rotation was applied in the next platform release.

For ExoPlayer, always propagating the rotation value doesn't seem like the right thing to do. That just moves the problem of working out what to do from the library to every individual application developer, who will then each have to figure out what different decoders do on different API levels. Instead, I think we probably want to work out what the current behaviors are and hardcode these inside the library, so that the rotation delivered to the application always ends up being correct (i.e. 0 when using a decoder that applied the rotation, non-zero otherwise). Hopefully we can also get consistent behavior across all video decoders from some version of the platform and above, since this makes the developer's life significantly easier.

Re-opening for tracking. First step is to try and figure out exactly what behavior we should be expecting across the various API levels / decoder implementations.

**Comment by dnutcracker** [comment]
Sounds good. Good luck :)

**Comment by jacekTymicki** [comment]
Do we have any timeline for fixing this issue?

**Comment by ojw28** [comment]
For most cases it is fixed already (the rotation will be applied, or propagated as unappliedRotationDegrees). So it's unclear exactly what you mean by this. Unless you've modified the player to use a software decoder then I think behavior should be correct already.

**Comment by jacekTymicki** [comment]
Defect with rotation is still reproducible on mp4 files that are rotated by 90 degres for versions lower lollipop e.g. on streaming of below link
http://cdn.steyapp.com/vid/178753/1e29b.mp4

I have latest version of source code with only one line changed in 
ExoPlayer\demo\src\main\java\com\google\android\exoplayer\demo\Samples.java
line 131
    new Sample("Dizzy", "http://cdn.steyapp.com/vid/178753/1e29b.mp4", PlayerActivity.TYPE_OTHER),

**Comment by ojw28** [comment]
It's not possible for us to rotate them automatically due to lack of platform support. Instead we report unappliedRotationDegrees=90. If the application is using TextureView then the app developer can apply a transformation to achieve the desired rotation. With SurfaceView rotation is not possible. See my comment on Aug 13th on this thread.

**Comment by dnutcracker** [comment]
FYI - I've tested the software decoder(OMX.google.h264.decoder) on the avd emulator with Nexus 5X running Android 6.0 and it looks like it doesn't apply the rotation. (a few remarks up you've said "It appears that on M+ OMX.google.h264.decoder does actually apply the rotation"...)

I don't know it it's platform issue or an emulator issue - Once I'll test it on a real nexus with Android 6.0 I'll update.

**Comment by ojw28** [comment]
What kind of Surface are you using (one from SurfaceView / TextureView / SomethingElse)?

**Comment by dnutcracker** [comment]
I'm using a TextureView

**Comment by sanjayharan** [comment]
Can any one post the working code with texture view?

**Comment by ojw28** [comment]
Use TextureView.setTransform and apply the rotation yourself.

**Comment by dnutcracker** [comment]
I know...This is what I've been doing all along...I just thought that I don't need to do it myself anymore on M+ after I've seen your comment about it - but I guess you were referring to SurfaceView...

**Comment by dnutcracker** [comment]
sanjayharan - once you know the correct video rotation (either by querying the video with MediaMetadataRetriever or via unappliedRotationDegrees passed to onVideoSizeChanged()) you create a transformation matrix with postRotate() and apply it to the textureview.

**Comment by dnutcracker** [comment]
Well - the plot thickens - seems like Android M's OMX.google.h264.decoder does not apply rotation when using ExoPlayer 1.4.2 but when using ExoPlayer 1.5.2 it does...how is that possible? I thought the platform's decoder is the one responsible for implementing the rotation....

**Comment by ojw28** [comment]
- The 21st post already states that the software decoder applies rotation on M+.
- The ExoPlayer fixes related to this change (and linked to from this issue) didn't land until 1.5.0.

**Comment by jacekTymicki** [comment]
@sanjayharan Example implementation could look like this:

public class VideoPlayer extends TextureView implements MediaCodecVideoTrackRenderer.EventListener,
		MediaCodecAudioTrackRenderer.EventListener {
...

	@Override
	public void onVideoSizeChanged(int width, int height, int unAppliedRotationDegrees, float pixelWidthHeightRatio) {
		int viewWidth = getWidth();
		int viewHeight = getHeight();

		float pivotX = viewWidth / 2f;
		float pivotY = viewHeight / 2f;

		Matrix transform = new Matrix();
		transform.postRotate(unAppliedRotationDegrees, pivotX, pivotY);
		if (unAppliedRotationDegrees == 90 || unAppliedRotationDegrees == 270) {
			float viewAspectRatio = (float) viewHeight / viewWidth;
			transform.postScale(1 / viewAspectRatio, viewAspectRatio, pivotX, pivotY);
		}
		setTransform(transform);
	}

**Comment by qqli007** [comment]
@jacekTymicki ,it need to fix scale if unAppliedRotationDegrees == 90.

**Comment by jacekTymicki** [comment]
You need to fix scaling when
unAppliedRotationDegrees == 90 or  unAppliedRotationDegrees == 270

**Comment by BackPackerDz** [comment]
I have the same issue, please any solution ?

**Comment by fasteque** [comment]
I see the same issue with the latest ExoPlayer version, `r2.0.0`: any solution while using the `SimpleExoPlayerView`?

**Comment by langrenfengzi** [comment]
So there was no ways to rotate a SurfaceView?

**Comment by helinfeng** [comment]
so i use the surfaceView,  so  i deep in dead end？？T_T

**Comment by rakshith-ravi** [comment]
Any update on this? I'm working on a commercial app and we kinda need this fixed ASAP. Would we see a fix anytime soon or would it be better to switch to a different solution for video playback?

**Comment by gabbimark** [comment]
same issue here. my videos playback correcly using any web or android video player that i try. But when playing back using exoplayer the videos are flipped 90 degrees on some phones. Will this be fixed soon?

**Comment by Ranjith121** [comment]
Same issue. Is any update on pre-L rotation?

**Comment by rakshith-ravi** [comment]
Considering I didn't see a fix, I moved to media player....The default solution for video playback. Would like to see a fix though

**Comment by Ranjith121** [comment]
ya am to moved to media player. thanks

**Comment by Satsrag** [comment]
int viewWidth = textureView.getWidth();
            int viewHeight = textureView.getHeight();
            Scale bestScale = getBestScale(new Size(width, height), new Size(viewWidth, viewHeight));
            float pivotX = viewWidth / 2f;
            float pivotY = viewHeight / 2f;
            Matrix transform = new Matrix();
            transform.postScale(bestScale.isW ? 1 : bestScale.scale, bestScale.isW ? bestScale.scale : 1, pivotX, pivotY);
            transform.postRotate(unAppliedRotationDegrees, pivotX, pivotY);
            if (unAppliedRotationDegrees == 90 || unAppliedRotationDegrees == 270) {
                final float scaledVideoWidth = bestScale.isW ? viewWidth : (viewWidth * bestScale.scale);
                final float scaledVideoHeight = bestScale.isW ? viewWidth * bestScale.scale : viewWidth;
                Scale scale = getBestScale(new Size((int) scaledVideoHeight, (int) scaledVideoWidth), new Size(viewWidth, viewHeight));
                transform.postScale(scale.scale, scale.scale, pivotX, pivotY);
            }
            if (textureView instanceof TextureView) {
                ((TextureView) textureView).setTransform(transform);
            }

**Comment by Kovartthan** [comment]
@Saqrag  your code makes correct rotation for the video in pre- lollipop versions ?

**Comment by crossle** [comment]
plz support display matrix rotation, like 
```
    for (i = 0; i < 3; i++) {
        display_matrix[i][0] = avio_rb32(pb);   // 16.16 fixed point
        display_matrix[i][1] = avio_rb32(pb);   // 16.16 fixed point
        display_matrix[i][2] = avio_rb32(pb);   //  2.30 fixed point
    }

```

**Comment by ArikYa** [comment]
Why doesn't SimpleExoPlayerView handle the rotation on older device? It already listens to the `onVideoSizeChanged()` and can handle it. As it stands, because it tries to handle the aspect ratio by itself, it prevents the application from doing it correctly

**Comment by ojw28** [comment]
We could (and probably should) do this if the `SimpleExoPlayerView` instance is configured to use `TextureView`. For `SurfaceView`, which is the default it's somewhat less clear what to do. We could just log a warning, or we could dynamically switch to `TextureView` for that specific case.

**Comment by ojw28** [comment]
@botaydotcom - Might be fun to take a look at.

**Comment by alexandreprado** [comment]
Hi guys!

Any update on this?

Thank you!

**Comment by botaydotcom** [comment]
We have updated `SimpleExoPlayerView` so that if it uses `TextureView`, it will apply the rotation automatically. This change will be pushed to dev-v2 branch soon.

**Comment by ojw28** [comment]
The change @botaydotcom mentions has now been pushed to `dev-v2`.

**Comment by shelarsuhas** [comment]
I have an application where I am using MediaRecorder to record a video and play it back using ExoPlayer. The video is recorded only in Portrait mode. I am setting the camera setRotation and MediaRecorder setOrientationHint appropriately, yet in some phones the video gets played in landscape mode.

I have checked the meta data of both the files where there is a rotation issue and where there is not and I can see that the rotation is indeed getting set to 270 degree as expected and I am still not getting the desired output.

![video_meta_data_image](https://user-images.githubusercontent.com/11662234/35608331-b2e51868-067e-11e8-9c51-82639a2d29f3.JPG)

The one on the left doesn't get played in correct orientation and the one on the right gets played. This is not specific to any particular API level.

**Comment by zagzy** [comment]
@botaydotcom great, that you have updated textureView.
Guys, what about rotation on SurfaceView? Any ideas?

**Comment by botaydotcom** [comment]
It's unfortunately not possible to do from application level (including from within ExoPlayer library) with `SurfaceView`. Please refer to @ojw28's comments in this thread.

If you use `SurfaceView` on L+, it should be applied automatically at platform level (note that there are a few issues with software decoders on L).
If you need to support `SurfaceView` on pre-L, one option is to detect if `unAppliedRotationDegrees` is not 0, and switch your app to use a `TextureView` dynamically, in which case ExoPlayer will handle the rotation for you automatically.
