### ISSUE TITLE
Cannot select any other than 1st audio/subtitle track in `StyledPlayerView` (regression)

### ISSUE THREAD

**Issue by moneytoo** [google/ExoPlayer#9649]
I'm migrating from ExoPlayer 2.15.1 to 2.16.0. When I select any audio or subtitle track (in `StyledPlayerView`), other than the first one, there is no audio heard or subtitle visible. I can replicate in something like this:

```java
public class MainActivity extends AppCompatActivity {

    private StyledPlayerView playerView;
    private ExoPlayer player;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        playerView = findViewById(R.id.video_view);

        MediaItem.Builder mediaItemBuilder = new MediaItem.Builder()
                .setUri(getIntent().getData())
                .setMimeType(getIntent().getType());

        player = new ExoPlayer.Builder(this)
                .build();

        playerView.setPlayer(player);

        player.setMediaItem(mediaItemBuilder.build());

        player.prepare();
    }
}
```

Video used for testing: https://github.com/ietf-wg-cellar/matroska-test-files/blob/master/test_files/test5.mkv

Steps:
1. Open test5.mkv
2. Change audio track from "Auto" to "Stereo" - it plays
3. Change audio track to "English, Mono" - it doesn't play

It's the same with subtitles. Only the first one (English) are visible. It works fine when using ExoPlayer 2.15.1.

- ExoPlayer version number: 2.16.0
- Android version: Android 10
- Android device: OnePlus 7

**Comment by tonihei** [comment]
I can reproduce the issue, thanks! Worth noting that this related to the built-in audio/text selection button in `StyledPlayerView`. Track selection via the ExoPlayer demo app debug controls still works as expected.

**Comment by tonihei** [comment]
Fixed by the commit above.

**Comment by rkarimi88** [comment]
Hi.
I'm using new version (2.16.0) and I still have the same problem (just for subtitles). When I switch subtitles to "None", I cannot switch it back to my subtitle anymore.
Is this problem solved? Shall I add any additional code to my app to fix it?

Thanks in advance.
